# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ee450c4c615454460542a42fb00b6bfbc16d2769c5639cd693ff9cb6dc2128e1f9778981273ae33f15baa73416dc8cf34cd7adcbb35bdad6069d0d7c45ef1d

test:
  secret_key_base: ea5d2a527f04068373de855aa1448206bc5acca683c949081265fbe152dc693179ca48a1560a783f03f5f9e6b05df1204a300df590daa3b64797645ec4e593e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
